// ============================================================
// Excel Import Type Definitions
// Generated by scripts/ingest-excel.ts
// All types represent the JSON shape written to data/excel-imports/
// ============================================================

// Shared metadata header on every output file
export type SheetMeta = {
  sheet_name: string;
  row_count: number;
  extracted_at: string; // ISO 8601
  warnings: string[];
};

// ──────────────────────────────────────────────
// Spell Vendors  →  spell-vendors.json
// ──────────────────────────────────────────────
export type SpellVendorRow = {
  _source_row: number;
  class: string;
  vendor_npc_name: string;
  location: string;
  floor_area: string;
  levels: string;
};

export type SpellVendorsOutput = SheetMeta & {
  records: SpellVendorRow[];
};

// ──────────────────────────────────────────────
// Tradeable Items & Schedule  →  tradeable-schedule.json
// ──────────────────────────────────────────────
export type TradeableScheduleRow = {
  _source_row: number;
  expansion: string;
  tradeable_items: string[];
  teek_schedule: string;
  unlock_date: string;
  epic_tradeables: string[];
};

export type TradeableScheduleOutput = SheetMeta & {
  records: TradeableScheduleRow[];
};

// ──────────────────────────────────────────────
// Epic 1.0 Quests  →  epic-quests.json
// ──────────────────────────────────────────────
export type EpicQuestStep = {
  _source_row: number;
  step: string | number;
  phase: string;
  action: string;
  npc_mob: string;
  zone: string;
  items: string;
  notes: string;
};

export type EpicQuestClass = {
  class_name: string;
  weapon_name: string;
  steps: EpicQuestStep[];
};

export type EpicQuestsOutput = SheetMeta & {
  classes: EpicQuestClass[];
};

// ──────────────────────────────────────────────
// Leveling Guide  →  leveling-guide.json
// ──────────────────────────────────────────────
export type LevelingGuideRow = {
  _source_row: number;
  section: string;
  level_range: string;
  zone: string;
  zem: number | null;
  play_style: string;
  why_its_good: string;
  tips: string;
  races_best_for: string;
};

export type LevelingGuideOutput = SheetMeta & {
  records: LevelingGuideRow[];
};

// ──────────────────────────────────────────────
// Zone XP Modifiers  →  zone-xp.json
// ──────────────────────────────────────────────
export type ZoneXpRow = {
  _source_row: number;
  zone: string;
  zem_value: number;
  bonus_pct: string;
  expansion: string;
  level_range: string;
  type: string;
  star_rating: string;
  star_count: number;
};

export type ZoneXpOutput = SheetMeta & {
  records: ZoneXpRow[];
};

// ──────────────────────────────────────────────
// Best in Slot Gear  →  bis-gear.json
// ──────────────────────────────────────────────
export type BisGearRow = {
  _source_row: number;
  section: string;
  item_name: string;
  haste_pct: string | null;
  slot: string;
  source: string;
  notes: string;
};

export type BisGearOutput = SheetMeta & {
  records: BisGearRow[];
};

// ──────────────────────────────────────────────
// Faction Guide  →  factions.json
// ──────────────────────────────────────────────
export type FactionSummaryRow = {
  _source_row: number;
  faction: string;
  leader: string;
  city: string;
  territory: string;
  armor_tier: string;
  armor_quality: string;
};

export type FactionDetailRow = {
  _source_row: number;
  section: string;
  content: string;
};

export type FactionsOutput = SheetMeta & {
  summary: FactionSummaryRow[];
  details: FactionDetailRow[];
};

// ──────────────────────────────────────────────
// PoP Progression Guide  →  pop-progression.json
// ──────────────────────────────────────────────
export type PopProgressionRow = {
  _source_row: number;
  step: number;
  zone_target: string;
  action: string;
  unlocks: string[];
  notes: string;
};

export type PopProgressionOutput = SheetMeta & {
  records: PopProgressionRow[];
};

// ──────────────────────────────────────────────
// Crafting sheets  →  crafting.json
// ──────────────────────────────────────────────
export type CraftingRecipeRow = {
  _source_row: number;
  craft_type: string;
  recipe_name: string;
  trivial: number | null;
  ingredients: string;
  category: string;
  notes: string;
  // Jewelcraft-specific extras
  metal_bar?: string;
  gem?: string;
  stats?: string;
};

export type CraftingOutput = SheetMeta & {
  craft_types: string[];
  records: CraftingRecipeRow[];
};

// ──────────────────────────────────────────────
// Normalization report  →  _normalization-report.json
// ──────────────────────────────────────────────
export type NormalizationMatch = {
  excel_name: string;
  source_sheet: string;
  source_row: number;
  status: "matched" | "not_found" | "partial";
  matched_name?: string;
  note?: string;
};

export type NormalizationReport = {
  generated_at: string;
  item_details_count: number;
  excel_items_checked: number;
  matched: number;
  not_found: number;
  partial: number;
  matches: NormalizationMatch[];
};
