// Generated by scripts/generate-pick-zones.mjs from data/ZoneNames.txt.
// Do not edit by hand; update the source text file and regenerate.

export type PickZone = {
  zoneId: number;
  zoneName: string;
  pickMin: number;
  pickMax: number;
  expansionStart: number;
  expansionEnd: number;
  expansionIds: readonly number[];
  expansionName: string;
  sourceLine: number;
};

export const pickExpansionNames = {
  "1": "Classic",
  "2": "Kunark",
  "3": "Velious",
  "4": "Luclin",
  "5": "Planes of Power",
  "6": "Legacy of Ykesha"
} as const;

export const pickZones = [
  {
    "zoneId": 36,
    "zoneName": "Befallen",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 32
  },
  {
    "zoneId": 17,
    "zoneName": "Blackburrow",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 15
  },
  {
    "zoneId": 68,
    "zoneName": "Butcherblock Mountains",
    "pickMin": 60,
    "pickMax": 180,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 61
  },
  {
    "zoneId": 58,
    "zoneName": "Clan Crushbone",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 51
  },
  {
    "zoneId": 70,
    "zoneName": "Dagnor's Cauldron",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 63
  },
  {
    "zoneId": 98,
    "zoneName": "Erud's Crossing",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 90
  },
  {
    "zoneId": 30,
    "zoneName": "Everfrost Peaks",
    "pickMin": 50,
    "pickMax": 150,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 27
  },
  {
    "zoneId": 384,
    "zoneName": "Freeport Sewers",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 326
  },
  {
    "zoneId": 6,
    "zoneName": "High Keep",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 5
  },
  {
    "zoneId": 407,
    "zoneName": "Highpass Hold",
    "pickMin": 25,
    "pickMax": 75,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 349
  },
  {
    "zoneId": 413,
    "zoneName": "Innothule Swamp",
    "pickMin": 50,
    "pickMax": 150,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 352
  },
  {
    "zoneId": 181,
    "zoneName": "Jaggedpine Forest",
    "pickMin": 50,
    "pickMax": 165,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 148
  },
  {
    "zoneId": 64,
    "zoneName": "Kedge Keep",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 57
  },
  {
    "zoneId": 20,
    "zoneName": "Kithicor Forest",
    "pickMin": 35,
    "pickMax": 105,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 18
  },
  {
    "zoneId": 51,
    "zoneName": "Lake Rathetear",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 45
  },
  {
    "zoneId": 415,
    "zoneName": "Misty Thicket",
    "pickMin": 40,
    "pickMax": 120,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 354
  },
  {
    "zoneId": 32,
    "zoneName": "Nagafen's Lair",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 29
  },
  {
    "zoneId": 44,
    "zoneName": "Najena",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 39
  },
  {
    "zoneId": 25,
    "zoneName": "Nektulos Forest",
    "pickMin": 55,
    "pickMax": 165,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 23
  },
  {
    "zoneId": 392,
    "zoneName": "North Desert of Ro",
    "pickMin": 35,
    "pickMax": 105,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 334
  },
  {
    "zoneId": 2,
    "zoneName": "North Qeynos",
    "pickMin": 30,
    "pickMax": 90,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 2
  },
  {
    "zoneId": 75,
    "zoneName": "Paineel",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 67
  },
  {
    "zoneId": 73,
    "zoneName": "Permafrost Keep",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 66
  },
  {
    "zoneId": 4,
    "zoneName": "Qeynos Hills",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 4
  },
  {
    "zoneId": 31,
    "zoneName": "Solusek's Eye",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 28
  },
  {
    "zoneId": 393,
    "zoneName": "South Desert of Ro",
    "pickMin": 50,
    "pickMax": 150,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 335
  },
  {
    "zoneId": 3,
    "zoneName": "Surefall Glade",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 3
  },
  {
    "zoneId": 48,
    "zoneName": "Temple of Cazic-Thule",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 42
  },
  {
    "zoneId": 59,
    "zoneName": "The Castle of Mistmoore",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 52
  },
  {
    "zoneId": 65,
    "zoneName": "The City of Guk",
    "pickMin": 30,
    "pickMax": 90,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 58
  },
  {
    "zoneId": 408,
    "zoneName": "The Commonlands",
    "pickMin": 55,
    "pickMax": 0,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 350
  },
  {
    "zoneId": 15,
    "zoneName": "The Eastern Plains of Karana",
    "pickMin": 30,
    "pickMax": 90,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 13
  },
  {
    "zoneId": 63,
    "zoneName": "The Estate of Unrest",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 56
  },
  {
    "zoneId": 47,
    "zoneName": "The Feerrott",
    "pickMin": 60,
    "pickMax": 180,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 41
  },
  {
    "zoneId": 886,
    "zoneName": "The Gifty Giver",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 658
  },
  {
    "zoneId": 16,
    "zoneName": "The Gorge of King Xorbb",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 14
  },
  {
    "zoneId": 54,
    "zoneName": "The Greater Faydark",
    "pickMin": 60,
    "pickMax": 180,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 48
  },
  {
    "zoneId": 18,
    "zoneName": "The Lair of the Splitpaw",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 16
  },
  {
    "zoneId": 27,
    "zoneName": "The Lavastorm Mountains",
    "pickMin": 40,
    "pickMax": 120,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 25
  },
  {
    "zoneId": 57,
    "zoneName": "The Lesser Faydark",
    "pickMin": 35,
    "pickMax": 105,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 50
  },
  {
    "zoneId": 11,
    "zoneName": "The Liberated Citadel of Runnyeye",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 9
  },
  {
    "zoneId": 13,
    "zoneName": "The Northern Plains of Karana",
    "pickMin": 25,
    "pickMax": 75,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 11
  },
  {
    "zoneId": 409,
    "zoneName": "The Ocean of Tears",
    "pickMin": 60,
    "pickMax": 180,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 351
  },
  {
    "zoneId": 72,
    "zoneName": "The Plane of Fear",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 65
  },
  {
    "zoneId": 186,
    "zoneName": "The Plane of Hate",
    "pickMin": 50,
    "pickMax": 0,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 150
  },
  {
    "zoneId": 45,
    "zoneName": "The Qeynos Aqueduct System",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 40
  },
  {
    "zoneId": 50,
    "zoneName": "The Rathe Mountains",
    "pickMin": 60,
    "pickMax": 180,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 44
  },
  {
    "zoneId": 66,
    "zoneName": "The Ruins of Old Guk",
    "pickMin": 30,
    "pickMax": 90,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 59
  },
  {
    "zoneId": 39,
    "zoneName": "The Ruins of Old Paineel",
    "pickMin": 40,
    "pickMax": 0,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 34
  },
  {
    "zoneId": 14,
    "zoneName": "The Southern Plains of Karana",
    "pickMin": 40,
    "pickMax": 120,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 12
  },
  {
    "zoneId": 448,
    "zoneName": "The Steamfont Mountains",
    "pickMin": 50,
    "pickMax": 150,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 387
  },
  {
    "zoneId": 100,
    "zoneName": "The Stonebrunt Mountains",
    "pickMin": 55,
    "pickMax": 165,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 91
  },
  {
    "zoneId": 101,
    "zoneName": "The Warrens",
    "pickMin": 30,
    "pickMax": 90,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 92
  },
  {
    "zoneId": 12,
    "zoneName": "The Western Plains of Karana",
    "pickMin": 45,
    "pickMax": 135,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 10
  },
  {
    "zoneId": 869,
    "zoneName": "Tides of Time",
    "pickMin": 25,
    "pickMax": 75,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 641
  },
  {
    "zoneId": 414,
    "zoneName": "Toxxulia Forest",
    "pickMin": 60,
    "pickMax": 180,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 353
  },
  {
    "zoneId": 383,
    "zoneName": "West Freeport",
    "pickMin": 50,
    "pickMax": 150,
    "expansionStart": 1,
    "expansionEnd": 1,
    "expansionIds": [
      1
    ],
    "expansionName": "Classic",
    "sourceLine": 325
  },
  {
    "zoneId": 103,
    "zoneName": "Chardok",
    "pickMin": 40,
    "pickMax": 120,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 94
  },
  {
    "zoneId": 277,
    "zoneName": "Chardok: The Halls of Betrayal",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 229
  },
  {
    "zoneId": 84,
    "zoneName": "Firiona Vie",
    "pickMin": 60,
    "pickMax": 180,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 76
  },
  {
    "zoneId": 92,
    "zoneName": "Frontier Mountains",
    "pickMin": 50,
    "pickMax": 150,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 84
  },
  {
    "zoneId": 105,
    "zoneName": "Howling Stones",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 96
  },
  {
    "zoneId": 88,
    "zoneName": "Kaesora",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 80
  },
  {
    "zoneId": 102,
    "zoneName": "Karnor's Castle",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 93
  },
  {
    "zoneId": 97,
    "zoneName": "Kurn's Tower",
    "pickMin": 30,
    "pickMax": 90,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 89
  },
  {
    "zoneId": 85,
    "zoneName": "Lake of Ill Omen",
    "pickMin": 60,
    "pickMax": 180,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 77
  },
  {
    "zoneId": 87,
    "zoneName": "The Burning Woods",
    "pickMin": 40,
    "pickMax": 120,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 79
  },
  {
    "zoneId": 90,
    "zoneName": "The City of Mist",
    "pickMin": 30,
    "pickMax": 90,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 82
  },
  {
    "zoneId": 104,
    "zoneName": "The Crypt of Dalnir",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 95
  },
  {
    "zoneId": 86,
    "zoneName": "The Dreadlands",
    "pickMin": 45,
    "pickMax": 0,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 78
  },
  {
    "zoneId": 94,
    "zoneName": "The Emerald Jungle",
    "pickMin": 40,
    "pickMax": 0,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 86
  },
  {
    "zoneId": 78,
    "zoneName": "The Field of Bone",
    "pickMin": 60,
    "pickMax": 180,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 70
  },
  {
    "zoneId": 107,
    "zoneName": "The Mines of Nurga",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 98
  },
  {
    "zoneId": 93,
    "zoneName": "The Overthere",
    "pickMin": 60,
    "pickMax": 180,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 85
  },
  {
    "zoneId": 89,
    "zoneName": "The Ruins of Sebilis",
    "pickMin": 30,
    "pickMax": 0,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 81
  },
  {
    "zoneId": 91,
    "zoneName": "The Skyfire Mountains",
    "pickMin": 40,
    "pickMax": 0,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 83
  },
  {
    "zoneId": 83,
    "zoneName": "The Swamp of No Hope",
    "pickMin": 60,
    "pickMax": 180,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 75
  },
  {
    "zoneId": 81,
    "zoneName": "The Temple of Droga",
    "pickMin": 55,
    "pickMax": 165,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 73
  },
  {
    "zoneId": 79,
    "zoneName": "The Warsliks Woods",
    "pickMin": 60,
    "pickMax": 180,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 71
  },
  {
    "zoneId": 96,
    "zoneName": "Timorous Deep",
    "pickMin": 45,
    "pickMax": 0,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 88
  },
  {
    "zoneId": 95,
    "zoneName": "Trakanon's Teeth",
    "pickMin": 40,
    "pickMax": 120,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 87
  },
  {
    "zoneId": 109,
    "zoneName": "Veksar",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 2,
    "expansionEnd": 2,
    "expansionIds": [
      2
    ],
    "expansionName": "Kunark",
    "sourceLine": 100
  },
  {
    "zoneId": 117,
    "zoneName": "Cobalt Scar",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 108
  },
  {
    "zoneId": 121,
    "zoneName": "Crystal Caverns",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 112
  },
  {
    "zoneId": 123,
    "zoneName": "Dragon Necropolis",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 113
  },
  {
    "zoneId": 116,
    "zoneName": "Eastern Wastes",
    "pickMin": 50,
    "pickMax": 150,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 107
  },
  {
    "zoneId": 129,
    "zoneName": "Icewell Keep",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 119
  },
  {
    "zoneId": 113,
    "zoneName": "Kael Drakkel",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 104
  },
  {
    "zoneId": 125,
    "zoneName": "Siren's Grotto",
    "pickMin": 25,
    "pickMax": 75,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 115
  },
  {
    "zoneId": 114,
    "zoneName": "Skyshrine",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 105
  },
  {
    "zoneId": 115,
    "zoneName": "The City of Thurgadin",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 106
  },
  {
    "zoneId": 118,
    "zoneName": "The Great Divide",
    "pickMin": 45,
    "pickMax": 0,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 109
  },
  {
    "zoneId": 110,
    "zoneName": "The Iceclad Ocean",
    "pickMin": 30,
    "pickMax": 0,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 101
  },
  {
    "zoneId": 124,
    "zoneName": "The Temple of Veeshan",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 114
  },
  {
    "zoneId": 111,
    "zoneName": "The Tower of Frozen Shadow",
    "pickMin": 25,
    "pickMax": 75,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 102
  },
  {
    "zoneId": 119,
    "zoneName": "The Wakening Land",
    "pickMin": 40,
    "pickMax": 0,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 110
  },
  {
    "zoneId": 120,
    "zoneName": "The Western Wastes",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 111
  },
  {
    "zoneId": 112,
    "zoneName": "Velketor's Labyrinth",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 3,
    "expansionEnd": 3,
    "expansionIds": [
      3
    ],
    "expansionName": "Velious",
    "sourceLine": 103
  },
  {
    "zoneId": 154,
    "zoneName": "Acrylia Caverns",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 124
  },
  {
    "zoneId": 174,
    "zoneName": "Dawnshroud Peaks",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 144
  },
  {
    "zoneId": 153,
    "zoneName": "Echo Caverns",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 123
  },
  {
    "zoneId": 163,
    "zoneName": "Grieg's End",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 133
  },
  {
    "zoneId": 167,
    "zoneName": "Grimling Forest",
    "pickMin": 35,
    "pickMax": 105,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 137
  },
  {
    "zoneId": 166,
    "zoneName": "Hollowshade Moor",
    "pickMin": 25,
    "pickMax": 75,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 136
  },
  {
    "zoneId": 160,
    "zoneName": "Katta Castellum",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 130
  },
  {
    "zoneId": 168,
    "zoneName": "Marus Seru",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 138
  },
  {
    "zoneId": 169,
    "zoneName": "Mons Letalis",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 139
  },
  {
    "zoneId": 161,
    "zoneName": "Netherbian Lair",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 131
  },
  {
    "zoneId": 156,
    "zoneName": "Paludal Caverns",
    "pickMin": 30,
    "pickMax": 90,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 126
  },
  {
    "zoneId": 159,
    "zoneName": "Sanctus Seru",
    "pickMin": 50,
    "pickMax": 0,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 129
  },
  {
    "zoneId": 165,
    "zoneName": "Shadeweaver's Thicket",
    "pickMin": 45,
    "pickMax": 135,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 135
  },
  {
    "zoneId": 162,
    "zoneName": "Ssraeshza Temple",
    "pickMin": 35,
    "pickMax": 0,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 132
  },
  {
    "zoneId": 179,
    "zoneName": "The Akheva Ruins",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 147
  },
  {
    "zoneId": 164,
    "zoneName": "The Deep",
    "pickMin": 30,
    "pickMax": 0,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 134
  },
  {
    "zoneId": 157,
    "zoneName": "The Fungus Grove",
    "pickMin": 25,
    "pickMax": 75,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 127
  },
  {
    "zoneId": 171,
    "zoneName": "The Grey",
    "pickMin": 25,
    "pickMax": 75,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 141
  },
  {
    "zoneId": 173,
    "zoneName": "The Maiden's Eye",
    "pickMin": 25,
    "pickMax": 75,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 143
  },
  {
    "zoneId": 175,
    "zoneName": "The Scarlet Desert",
    "pickMin": 40,
    "pickMax": 120,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 145
  },
  {
    "zoneId": 172,
    "zoneName": "The Tenebrous Mountains",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 142
  },
  {
    "zoneId": 170,
    "zoneName": "The Twilight Sea",
    "pickMin": 30,
    "pickMax": 90,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 140
  },
  {
    "zoneId": 176,
    "zoneName": "The Umbral Plains",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 4,
    "expansionEnd": 4,
    "expansionIds": [
      4
    ],
    "expansionName": "Luclin",
    "sourceLine": 146
  },
  {
    "zoneId": 217,
    "zoneName": "Doomfire, the Burning Lands",
    "pickMin": 40,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 169
  },
  {
    "zoneId": 214,
    "zoneName": "Drunder, the Fortress of Zek",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 166
  },
  {
    "zoneId": 215,
    "zoneName": "Eryslai, the Kingdom of Wind",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 167
  },
  {
    "zoneId": 200,
    "zoneName": "Ruins of Lxanvom",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 152
  },
  {
    "zoneId": 211,
    "zoneName": "The Halls of Honor",
    "pickMin": 30,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 163
  },
  {
    "zoneId": 205,
    "zoneName": "The Plane of Disease",
    "pickMin": 30,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 157
  },
  {
    "zoneId": 206,
    "zoneName": "The Plane of Innovation",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 158
  },
  {
    "zoneId": 210,
    "zoneName": "The Plane of Storms",
    "pickMin": 40,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 162
  },
  {
    "zoneId": 203,
    "zoneName": "The Plane of Tranquility",
    "pickMin": 200,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 155
  },
  {
    "zoneId": 208,
    "zoneName": "The Plane of Valor",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 160
  },
  {
    "zoneId": 216,
    "zoneName": "The Reef of Coirnav",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 168
  },
  {
    "zoneId": 212,
    "zoneName": "The Tower of Solusek Ro",
    "pickMin": 30,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 164
  },
  {
    "zoneId": 209,
    "zoneName": "Torden, the Bastion of Thunder",
    "pickMin": 35,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 161
  },
  {
    "zoneId": 207,
    "zoneName": "Torment, the Plane of Pain",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 159
  },
  {
    "zoneId": 218,
    "zoneName": "Vegarlson, The Earthen Badlands",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 5,
    "expansionEnd": 5,
    "expansionIds": [
      5
    ],
    "expansionName": "Planes of Power",
    "sourceLine": 170
  },
  {
    "zoneId": 225,
    "zoneName": "Dulak's Harbor",
    "pickMin": 45,
    "pickMax": 135,
    "expansionStart": 6,
    "expansionEnd": 6,
    "expansionIds": [
      6
    ],
    "expansionName": "Legacy of Ykesha",
    "sourceLine": 177
  },
  {
    "zoneId": 228,
    "zoneName": "Hate's Fury",
    "pickMin": 20,
    "pickMax": 0,
    "expansionStart": 6,
    "expansionEnd": 6,
    "expansionIds": [
      6
    ],
    "expansionName": "Legacy of Ykesha",
    "sourceLine": 180
  },
  {
    "zoneId": 278,
    "zoneName": "The Caverns of Exile",
    "pickMin": 25,
    "pickMax": 0,
    "expansionStart": 6,
    "expansionEnd": 6,
    "expansionIds": [
      6
    ],
    "expansionName": "Legacy of Ykesha",
    "sourceLine": 230
  },
  {
    "zoneId": 227,
    "zoneName": "The Crypt of Nadox",
    "pickMin": 25,
    "pickMax": 75,
    "expansionStart": 6,
    "expansionEnd": 6,
    "expansionIds": [
      6
    ],
    "expansionName": "Legacy of Ykesha",
    "sourceLine": 179
  },
  {
    "zoneId": 224,
    "zoneName": "The Gulf of Gunthak",
    "pickMin": 40,
    "pickMax": 120,
    "expansionStart": 6,
    "expansionEnd": 6,
    "expansionIds": [
      6
    ],
    "expansionName": "Legacy of Ykesha",
    "sourceLine": 176
  },
  {
    "zoneId": 226,
    "zoneName": "The Torgiran Mines",
    "pickMin": 20,
    "pickMax": 60,
    "expansionStart": 6,
    "expansionEnd": 6,
    "expansionIds": [
      6
    ],
    "expansionName": "Legacy of Ykesha",
    "sourceLine": 178
  }
] as const satisfies PickZone[];

export const pickZoneGenerationStats = {
  "source": "data/ZoneNames.txt",
  "included": 142,
  "skippedMalformed": 12,
  "skippedNoPickMin": 298,
  "skippedExpansion": 211
} as const;
